a= 3
b= 12
print("Mathematical Operators...")
print(a+b)
print(b-a)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(b/a)
print(b//a)
print(a%b)
print(b%a)
print(a**b)
print(a**a)
print(b**b)
print(b**a)
print()
print(a+b/3-4*12) #without any parenthesis
print((a+b)/3-(4*12))
print(a+(b/3)-(4*12))
print(((a+b)/3-4)*12)
