
parrot= "Norwegian Blue"
print("Positive")
print(parrot[3].upper())
print(parrot[4])
print(parrot[9])
print(parrot[3])
print(parrot[6])
print(parrot[8])
print()
print("Negative")
print(parrot[-11].upper())
print(parrot[-1])
print(parrot[-5])
print(parrot[-11])
print(parrot[-8])
print(parrot[-6])
print("size")
print(len(parrot))